<a href="https://colab.research.google.com/github/luisfmnunes/LinearAlgebra/blob/main/LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Determinants
Determinants represent a propertie from matrixes that carry a whole lot of information about these matrixes (such as if it is invertible or singular, representing the matriz volume, etc) and are further used for the development of other properties such as eigenvalues.

This notebook aims to implement the determinant calculation of any **n** x **n** matrix using cofactors algorithm.


In [1]:
import numpy as np

In [2]:
def is_square(matrix):
  if isinstance(matrix, list):
    matrix = np.array(matrix)
  if isinstance(matrix, np.ndarray):
    if (len(matrix.shape) != 2):
      raise ValueError(f"Matrix Dimension mismatch. Expected 2, got {len(matrix.shape)}.")
    if not (matrix.shape[0] == matrix.shape[1]):
      raise ValueError(f"Matrix isn't Square. ({matrix.shape[0]}x{matrix.shape[1]})")
  else:
    raise ValueError(f"Expected list/ndarray types got {type(matrix)}")
  return True

## Cofactoring

The idea of cofactoring the matrix consists in reducing the dimensionality of the matrix by one by using one of the properties of the deteminant, property 3(b) according to Gilbert Strang.

In [3]:
def get_cofactor(matrix, row, col):
  return np.delete(np.delete(matrix, row, axis=0), col, axis=1)

In [4]:
# def cofactor(matrix, i, j):
  

In [17]:
def determinant(matrix):
  if matrix.size == 0:
    return 1
  sum = 0
  for j, m_ij in enumerate(matrix[0]):
      # if not m_ij:
      #   sum = 0
      #   break
      # else:
        sum += (-1)**(j)*m_ij*determinant(get_cofactor(matrix, 0, j))
  return sum

In [6]:
r = np.random.randn(3,3)

In [7]:
determinant(np.array([[1,2],[3,4]]))

-2

In [8]:
determinant(np.array([[5,4,3],[1,1,1],[1,2,1]]))

-2

In [9]:
determinant(np.array([[1,1,1],[2,2,2],[4,7,9]]))

0

# Inverse Matrix by Determinant

Well, one of the properties of the determinant easily proven by the properties of the determinant is that the inverse matrix can be obtained by the following expression:

<p align=center>
  <img src="https://latex.codecogs.com/svg.image?A^{-1}&space;=&space;\frac{1}{det(A)}C^{T}">
</p>

This matrix C is called the minor-matrix composed by the determinant of the cofactors from each position in the matrix. The cofactor matrix is the resultant value after applying the signals according if the sum of column and row index is odd or even. Finally by transposing the cofactor matrix (C<sup>T</sup>), the inverser matrix is obtained by dividing the cofactor matrix from the determinant of the original matrix.

In [23]:
def inverse_matrix(matrix):
  det = determinant(matrix)
  if not det:
    raise ValueError("Singular Matrix isn't inversible!!")
  cofat = np.zeros(matrix.shape)
  for i, row in enumerate(matrix):
    for j, _ in enumerate(row):
      cofat[j,i] = (-1)**(i+j)*determinant(get_cofactor(matrix,i,j))

  return cofat/det

In [24]:
A = np.array([[3, 0, 2],
              [2, 0, -2],
              [0, 1, 1]])
A_inv = inverse_matrix(A)
print(A_inv)

[[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3  0. ]]


In [27]:
B = np.array([[1,1,0,0],
              [0,1,1,0],
              [1,0,0,1],
              [0,1,0,1]])
B_inv = inverse_matrix(B)
print(f"det B = {determinant(B)} \n {B} \n det B^(-1) = {determinant(B_inv)} \n {B_inv}")

det B = 2 
 [[1 1 0 0]
 [0 1 1 0]
 [1 0 0 1]
 [0 1 0 1]] 
 det B^(-1) = 0.5 
 [[ 0.5  0.   0.5 -0.5]
 [ 0.5  0.  -0.5  0.5]
 [-0.5  1.   0.5 -0.5]
 [-0.5  0.   0.5  0.5]]
